bottleneck_dim: 191
n_enc_layers: 5
n_dec_layers: 3
base_channels: 35
growth_factor: 2.568614041926561
use_batchnorm: true
use_hpf: false
hpf_sigma: 3.0
lr: 1.939338177236105e-05
batch_size: 32
max_epochs: 300
min_epochs: 30
patience: 30
seed: 42
deterministic: false
manifests_dir: /mnt/beegfs/mantis/jrathi/AE_Model_Thesis/manifests
images_root: /mnt/beegfs/mantis/jrathi/AE_Model_Thesis/AEModel_jy_screenshots
crop_box:
- 72
- 28
- 300
- 500
image_size: 256
score_k: 37.0
output_dir: outputs
trial_num: 110
