bottleneck_dim: 170
n_enc_layers: 5
n_dec_layers: 5
base_channels: 37
growth_factor: 1.5423636305785342
use_batchnorm: true
use_hpf: true
hpf_sigma: 1.1217772324077675
lr: 1.0491812281145558e-05
batch_size: 48
max_epochs: 300
min_epochs: 30
patience: 30
seed: 42
deterministic: false
manifests_dir: /mnt/beegfs/mantis/jrathi/AE_Model_Thesis/manifests
images_root: /mnt/beegfs/mantis/jrathi/AE_Model_Thesis/AEModel_jy_screenshots
crop_box:
- 72
- 28
- 300
- 500
image_size: 256
score_k: 37.0
output_dir: outputs
trial_num: 69
