bottleneck_dim: 149
n_enc_layers: 4
n_dec_layers: 5
base_channels: 23
growth_factor: 1.5532657748922831
use_batchnorm: true
use_hpf: false
hpf_sigma: 3.0
lr: 6.261668226905696e-05
batch_size: 48
max_epochs: 300
min_epochs: 30
patience: 30
seed: 42
deterministic: false
manifests_dir: /mnt/beegfs/mantis/jrathi/AE_Model_Thesis/manifests
images_root: /mnt/beegfs/mantis/jrathi/AE_Model_Thesis/AEModel_jy_screenshots
crop_box:
- 72
- 28
- 300
- 500
image_size: 256
score_k: 37.0
output_dir: outputs
trial_num: 133
