bottleneck_dim: 151
n_enc_layers: 4
n_dec_layers: 5
base_channels: 17
growth_factor: 2.6680100759396126
use_batchnorm: true
use_hpf: true
hpf_sigma: 5.770387855769913
lr: 0.00014152342421804996
batch_size: 64
max_epochs: 300
min_epochs: 30
patience: 30
seed: 42
deterministic: false
manifests_dir: /mnt/beegfs/mantis/jrathi/AE_Model_Thesis/manifests
images_root: /mnt/beegfs/mantis/jrathi/AE_Model_Thesis/AEModel_jy_screenshots
crop_box:
- 72
- 28
- 300
- 500
image_size: 256
score_k: 37.0
output_dir: outputs
trial_num: 12
