bottleneck_dim: 153
n_enc_layers: 4
n_dec_layers: 2
base_channels: 22
growth_factor: 1.867599448154543
use_batchnorm: false
use_hpf: true
hpf_sigma: 1.6020369817067728
lr: 0.00031405723427388265
batch_size: 24
max_epochs: 300
min_epochs: 30
patience: 30
seed: 42
deterministic: false
manifests_dir: /mnt/beegfs/mantis/jrathi/AE_Model_Thesis/manifests
images_root: /mnt/beegfs/mantis/jrathi/AE_Model_Thesis/AEModel_jy_screenshots
crop_box:
- 72
- 28
- 300
- 500
image_size: 256
score_k: 37.0
output_dir: outputs
trial_num: 16
