bottleneck_dim: 130
n_enc_layers: 2
n_dec_layers: 4
base_channels: 44
growth_factor: 2.332499671424319
use_batchnorm: true
use_hpf: true
hpf_sigma: 1.0406328306493473
lr: 0.0007095198681416727
batch_size: 8
max_epochs: 300
min_epochs: 30
patience: 30
seed: 42
deterministic: false
manifests_dir: /mnt/beegfs/mantis/jrathi/AE_Model_Thesis/manifests
images_root: /mnt/beegfs/mantis/jrathi/AE_Model_Thesis/AEModel_jy_screenshots
crop_box:
- 72
- 28
- 300
- 500
image_size: 256
score_k: 37.0
output_dir: outputs
trial_num: 171
